package com.QLDVSpringMVC.model;
// Generated 22-May-2021, 2:33:20 pm by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Chidoan generated by hbm2java
 */
@Entity
@Table(name = "chidoan", catalog = "quanlydoanvien")
public class Chidoan implements java.io.Serializable {

	private int machidoan;
	private Khoa khoa;
	private String tenchidoan;
	private String chidoantruong;
	private Boolean trangthai;
	private Set<Taikhoan> taikhoans = new HashSet<Taikhoan>(0);

	public Chidoan() {
	}

	public Chidoan(int machidoan) {
		this.machidoan = machidoan;
	}

	public Chidoan(int machidoan, Khoa khoa, String tenchidoan, Boolean trangthai,String chidoantruong, Set<Taikhoan> taikhoans) {
		this.machidoan = machidoan;
		this.khoa = khoa;
		this.tenchidoan = tenchidoan;
		this.trangthai = trangthai;
		this.chidoantruong = chidoantruong;
		this.taikhoans = taikhoans;
	}

	@Id

	@Column(name = "Machidoan", unique = true, nullable = false)
	public int getMachidoan() {
		return this.machidoan;
	}

	public void setMachidoan(int machidoan) {
		this.machidoan = machidoan;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Makhoa")
	public Khoa getKhoa() {
		return this.khoa;
	}

	public void setKhoa(Khoa khoa) {
		this.khoa = khoa;
	}

	@Column(name = "Tenchidoan", length = 15)
	public String getTenchidoan() {
		return this.tenchidoan;
	}

	public void setTenchidoan(String tenchidoan) {
		this.tenchidoan = tenchidoan;
	}

	@Column(name = "Trangthai")
	public Boolean getTrangthai() {
		return this.trangthai;
	}

	public void setTrangthai(Boolean trangthai) {
		this.trangthai = trangthai;
	}
	@Column(name = "Chidoantruong")
	public String getChidoantruong() {
		return this.chidoantruong;
	}

	public void setChidoantruong(String chidoantruong) {
		this.chidoantruong = chidoantruong;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chidoan")
	public Set<Taikhoan> getTaikhoans() {
		return this.taikhoans;
	}

	public void setTaikhoans(Set<Taikhoan> taikhoans) {
		this.taikhoans = taikhoans;
	}

}
