package com.QLDVSpringMVC.model;
// Generated 22-May-2021, 2:33:20 pm by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CtHoatdong generated by hbm2java
 */
@Entity
@Table(name = "ct_hoatdong", catalog = "quanlydoanvien")
public class CtHoatdong implements java.io.Serializable {

	private CtHoatdongId id;
	private Hoatdong hoatdong;
	private Taikhoan taikhoan;
	private String ngayThamgia;
	private String ngayKetThuc;

	public CtHoatdong() {
	}

	public CtHoatdong(CtHoatdongId id, Hoatdong hoatdong, Taikhoan taikhoan) {
		this.id = id;
		this.hoatdong = hoatdong;
		this.taikhoan = taikhoan;
	}

	public CtHoatdong(CtHoatdongId id, Hoatdong hoatdong, Taikhoan taikhoan, String ngayThamgia, String ngayKetThuc) {
		this.id = id;
		this.hoatdong = hoatdong;
		this.taikhoan = taikhoan;
		this.ngayThamgia = ngayThamgia;
		this.ngayKetThuc = ngayKetThuc;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "maHd", column = @Column(name = "MaHD", nullable = false)),
			@AttributeOverride(name = "maTk", column = @Column(name = "MaTK", nullable = false, length = 10)) })
	public CtHoatdongId getId() {
		return this.id;
	}

	public void setId(CtHoatdongId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaHD", nullable = false, insertable = false, updatable = false)
	public Hoatdong getHoatdong() {
		return this.hoatdong;
	}

	public void setHoatdong(Hoatdong hoatdong) {
		this.hoatdong = hoatdong;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaTK", nullable = false, insertable = false, updatable = false)
	public Taikhoan getTaikhoan() {
		return this.taikhoan;
	}

	public void setTaikhoan(Taikhoan taikhoan) {
		this.taikhoan = taikhoan;
	}

	@Column(name = "NgayThamgia", length = 10)
	public String getNgayThamgia() {
		return this.ngayThamgia;
	}

	public void setNgayThamgia(String ngayThamgia) {
		this.ngayThamgia = ngayThamgia;
	}

	@Column(name = "NgayKetThuc", length = 10)
	public String getNgayKetThuc() {
		return this.ngayKetThuc;
	}

	public void setNgayKetThuc(String ngayKetThuc) {
		this.ngayKetThuc = ngayKetThuc;
	}

}
