package com.QLDVSpringMVC.model;
// Generated 22-May-2021, 2:33:20 pm by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CtHoatdongId generated by hbm2java
 */
@Embeddable
public class CtHoatdongId implements java.io.Serializable {

	private int maHd;
	private String maTk;

	public CtHoatdongId() {
	}

	public CtHoatdongId(int maHd, String maTk) {
		this.maHd = maHd;
		this.maTk = maTk;
	}

	@Column(name = "MaHD", nullable = false)
	public int getMaHd() {
		return this.maHd;
	}

	public void setMaHd(int maHd) {
		this.maHd = maHd;
	}

	@Column(name = "MaTK", nullable = false, length = 10)
	public String getMaTk() {
		return this.maTk;
	}

	public void setMaTk(String maTk) {
		this.maTk = maTk;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CtHoatdongId))
			return false;
		CtHoatdongId castOther = (CtHoatdongId) other;

		return (this.getMaHd() == castOther.getMaHd())
				&& ((this.getMaTk() == castOther.getMaTk()) || (this.getMaTk() != null && castOther.getMaTk() != null
						&& this.getMaTk().equals(castOther.getMaTk())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMaHd();
		result = 37 * result + (getMaTk() == null ? 0 : this.getMaTk().hashCode());
		return result;
	}

}
