package com.QLDVSpringMVC.model;
// Generated 22-May-2021, 2:33:20 pm by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Diemdv generated by hbm2java
 */
@Entity
@Table(name = "diemdv", catalog = "quanlydoanvien")
public class Diemdv implements java.io.Serializable {

	private DiemdvId id;
	private Taikhoan taikhoan;
	private TieuchiDiemrenluyen tieuchiDiemrenluyen;
	private Integer sodiem;

	public Diemdv() {
	}

	public Diemdv(DiemdvId id, Taikhoan taikhoan, TieuchiDiemrenluyen tieuchiDiemrenluyen) {
		this.id = id;
		this.taikhoan = taikhoan;
		this.tieuchiDiemrenluyen = tieuchiDiemrenluyen;
	}

	public Diemdv(DiemdvId id, Taikhoan taikhoan, TieuchiDiemrenluyen tieuchiDiemrenluyen, Integer sodiem) {
		this.id = id;
		this.taikhoan = taikhoan;
		this.tieuchiDiemrenluyen = tieuchiDiemrenluyen;
		this.sodiem = sodiem;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idPhieuTc", column = @Column(name = "IdPhieu_TC", nullable = false)),
			@AttributeOverride(name = "maTk", column = @Column(name = "MaTK", nullable = false, length = 10)),
			@AttributeOverride(name = "machucvu", column = @Column(name = "Machucvu", nullable = false)) })
	public DiemdvId getId() {
		return this.id;
	}

	public void setId(DiemdvId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaTK", nullable = false, insertable = false, updatable = false)
	public Taikhoan getTaikhoan() {
		return this.taikhoan;
	}

	public void setTaikhoan(Taikhoan taikhoan) {
		this.taikhoan = taikhoan;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdPhieu_TC", nullable = false, insertable = false, updatable = false)
	public TieuchiDiemrenluyen getTieuchiDiemrenluyen() {
		return this.tieuchiDiemrenluyen;
	}

	public void setTieuchiDiemrenluyen(TieuchiDiemrenluyen tieuchiDiemrenluyen) {
		this.tieuchiDiemrenluyen = tieuchiDiemrenluyen;
	}

	@Column(name = "Sodiem")
	public Integer getSodiem() {
		return this.sodiem;
	}

	public void setSodiem(Integer sodiem) {
		this.sodiem = sodiem;
	}

}
