package com.QLDVSpringMVC.model;
// Generated 22-May-2021, 2:33:20 pm by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Doanphi generated by hbm2java
 */
@Entity
@Table(name = "doanphi", catalog = "quanlydoanvien")
public class Doanphi implements java.io.Serializable {

	private int maphieu;
	private Taikhoan taikhoan;
	private String namhoc;
	private Boolean trangthai;

	public Doanphi() {
	}

	public Doanphi(int maphieu) {
		this.maphieu = maphieu;
	}

	public Doanphi(int maphieu, Taikhoan taikhoan, String namhoc, Boolean trangthai) {
		this.maphieu = maphieu;
		this.taikhoan = taikhoan;
		this.namhoc = namhoc;
		this.trangthai = trangthai;
	}

	@Id

	@Column(name = "Maphieu", unique = true, nullable = false)
	public int getMaphieu() {
		return this.maphieu;
	}

	public void setMaphieu(int maphieu) {
		this.maphieu = maphieu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Madoanvien")
	public Taikhoan getTaikhoan() {
		return this.taikhoan;
	}

	public void setTaikhoan(Taikhoan taikhoan) {
		this.taikhoan = taikhoan;
	}

	@Column(name = "Namhoc", length = 10)
	public String getNamhoc() {
		return this.namhoc;
	}

	public void setNamhoc(String namhoc) {
		this.namhoc = namhoc;
	}

	@Column(name = "Trangthai")
	public Boolean getTrangthai() {
		return this.trangthai;
	}

	public void setTrangthai(Boolean trangthai) {
		this.trangthai = trangthai;
	}

}
