package com.QLDVSpringMVC.model;
// Generated 22-May-2021, 2:33:20 pm by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Hocky generated by hbm2java
 */
@Entity
@Table(name = "hocky", catalog = "quanlydoanvien")
public class Hocky implements java.io.Serializable {

	private String maHk;
	private String namhoc;
	private String tenHk;
	private Set<PhieuDrl> phieuDrls = new HashSet<PhieuDrl>(0);

	public Hocky() {
	}

	public Hocky(String maHk) {
		this.maHk = maHk;
	}

	public Hocky(String maHk, String namhoc, String tenHk, Set<PhieuDrl> phieuDrls) {
		this.maHk = maHk;
		this.namhoc = namhoc;
		this.tenHk = tenHk;
		this.phieuDrls = phieuDrls;
	}

	@Id

	@Column(name = "MaHK", unique = true, nullable = false, length = 10)
	public String getMaHk() {
		return this.maHk;
	}

	public void setMaHk(String maHk) {
		this.maHk = maHk;
	}

	@Column(name = "Namhoc", length = 10)
	public String getNamhoc() {
		return this.namhoc;
	}

	public void setNamhoc(String namhoc) {
		this.namhoc = namhoc;
	}

	@Column(name = "TenHK", length = 30)
	public String getTenHk() {
		return this.tenHk;
	}

	public void setTenHk(String tenHk) {
		this.tenHk = tenHk;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hocky")
	public Set<PhieuDrl> getPhieuDrls() {
		return this.phieuDrls;
	}

	public void setPhieuDrls(Set<PhieuDrl> phieuDrls) {
		this.phieuDrls = phieuDrls;
	}

}
