package com.QLDVSpringMVC.model;
// Generated 22-May-2021, 2:33:20 pm by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Loaidiem generated by hbm2java
 */
@Entity
@Table(name = "loaidiem", catalog = "quanlydoanvien")
public class Loaidiem implements java.io.Serializable {

	private int maloaidiem;
	private String tengoi;

	public Loaidiem() {
	}

	public Loaidiem(int maloaidiem) {
		this.maloaidiem = maloaidiem;
	}

	public Loaidiem(int maloaidiem, String tengoi) {
		this.maloaidiem = maloaidiem;
		this.tengoi = tengoi;
	}

	@Id

	@Column(name = "Maloaidiem", unique = true, nullable = false)
	public int getMaloaidiem() {
		return this.maloaidiem;
	}

	public void setMaloaidiem(int maloaidiem) {
		this.maloaidiem = maloaidiem;
	}

	@Column(name = "Tengoi", length = 20)
	public String getTengoi() {
		return this.tengoi;
	}

	public void setTengoi(String tengoi) {
		this.tengoi = tengoi;
	}

}
