package com.QLDVSpringMVC.model;
// Generated 22-May-2021, 2:33:20 pm by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PhieuDrl generated by hbm2java
 */
@Entity
@Table(name = "phieu_drl", catalog = "quanlydoanvien")
public class PhieuDrl implements java.io.Serializable {

	private String maphieu;
	private Hocky hocky;
	private String ngaytao;
	private Set<TieuchiDiemrenluyen> tieuchiDiemrenluyens = new HashSet<TieuchiDiemrenluyen>(0);

	public PhieuDrl() {
	}

	public PhieuDrl(String maphieu) {
		this.maphieu = maphieu;
	}

	public PhieuDrl(String maphieu, Hocky hocky, String ngaytao, Set<TieuchiDiemrenluyen> tieuchiDiemrenluyens) {
		this.maphieu = maphieu;
		this.hocky = hocky;
		this.ngaytao = ngaytao;
		this.tieuchiDiemrenluyens = tieuchiDiemrenluyens;
	}

	@Id

	@Column(name = "Maphieu", unique = true, nullable = false, length = 10)
	public String getMaphieu() {
		return this.maphieu;
	}

	public void setMaphieu(String maphieu) {
		this.maphieu = maphieu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MaHK")
	public Hocky getHocky() {
		return this.hocky;
	}

	public void setHocky(Hocky hocky) {
		this.hocky = hocky;
	}

	@Column(name = "Ngaytao", length = 10)
	public String getNgaytao() {
		return this.ngaytao;
	}

	public void setNgaytao(String ngaytao) {
		this.ngaytao = ngaytao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phieuDrl")
	public Set<TieuchiDiemrenluyen> getTieuchiDiemrenluyens() {
		return this.tieuchiDiemrenluyens;
	}

	public void setTieuchiDiemrenluyens(Set<TieuchiDiemrenluyen> tieuchiDiemrenluyens) {
		this.tieuchiDiemrenluyens = tieuchiDiemrenluyens;
	}

}
