package com.QLDVSpringMVC.model;
// Generated 22-May-2021, 2:33:20 pm by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Taikhoan generated by hbm2java
 */
@Entity
@Table(name = "taikhoan", catalog = "quanlydoanvien")
public class Taikhoan implements java.io.Serializable {

	private String username;
	private Chidoan chidoan;
	private Chucvu chucvu;
	private String hoten;
	private String ngaysinh;
	private Boolean gioitinh;
	private String dantoc;
	private String theDoan;
	private String soDoan;
	private Boolean khaitru;
	private String thanhpho;
	private String quanhuyen;
	private String diachi;
	private String sdt;
	private String password;
	private Set<Doanphi> doanphis = new HashSet<Doanphi>(0);
	private Set<Diemdv> diemdvs = new HashSet<Diemdv>(0);
	private Set<Tintuc> tintucs = new HashSet<Tintuc>(0);
	private Set<CtHoatdong> ctHoatdongs = new HashSet<CtHoatdong>(0);

	public Taikhoan() {
	}

	public Taikhoan(String username, Chucvu chucvu) {
		this.username = username;
		this.chucvu = chucvu;
	}

	public Taikhoan(String username, Chidoan chidoan, Chucvu chucvu, String hoten, String ngaysinh, Boolean gioitinh,
			String dantoc, String theDoan, String soDoan, Boolean khaitru, String diachi, String sdt, String password,
			Set<Doanphi> doanphis, Set<Diemdv> diemdvs, Set<Tintuc> tintucs, Set<CtHoatdong> ctHoatdongs) {
		this.username = username;
		this.chidoan = chidoan;
		this.chucvu = chucvu;
		this.hoten = hoten;
		this.ngaysinh = ngaysinh;
		this.gioitinh = gioitinh;
		this.dantoc = dantoc;
		this.theDoan = theDoan;
		this.soDoan = soDoan;
		this.khaitru = khaitru;
		this.diachi = diachi;
		this.sdt = sdt;
		this.password = password;
		this.doanphis = doanphis;
		this.diemdvs = diemdvs;
		this.tintucs = tintucs;
		this.ctHoatdongs = ctHoatdongs;
	}

	@Id

	@Column(name = "MaTK", unique = true, nullable = false, length = 10)
	public String getusername() {
		return this.username;
	}

	public void setusername(String username) {
		this.username = username;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Machidoan")
	public Chidoan getChidoan() {
		return this.chidoan;
	}

	public void setChidoan(Chidoan chidoan) {
		this.chidoan = chidoan;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Machucvu", nullable = false)
	public Chucvu getChucvu() {
		return this.chucvu;
	}

	public void setChucvu(Chucvu chucvu) {
		this.chucvu = chucvu;
	}

	@Column(name = "Hoten", length = 50)
	public String getHoten() {
		return this.hoten;
	}

	public void setHoten(String hoten) {
		this.hoten = hoten;
	}

	@Column(name = "Ngaysinh", length = 11)
	public String getNgaysinh() {
		return this.ngaysinh;
	}

	public void setNgaysinh(String ngaysinh) {
		this.ngaysinh = ngaysinh;
	}

	@Column(name = "Gioitinh")
	public Boolean getGioitinh() {
		return this.gioitinh;
	}

	public void setGioitinh(Boolean gioitinh) {
		this.gioitinh = gioitinh;
	}

	@Column(name = "Dantoc", length = 20)
	public String getDantoc() {
		return this.dantoc;
	}

	public void setDantoc(String dantoc) {
		this.dantoc = dantoc;
	}

	@Column(name = "TheDoan", length = 10)
	public String getTheDoan() {
		return this.theDoan;
	}

	public void setTheDoan(String theDoan) {
		this.theDoan = theDoan;
	}

	@Column(name = "SoDoan", length = 10)
	public String getSoDoan() {
		return this.soDoan;
	}

	public void setSoDoan(String soDoan) {
		this.soDoan = soDoan;
	}

	@Column(name = "Khaitru")
	public Boolean getKhaitru() {
		return this.khaitru;
	}

	public void setKhaitru(Boolean khaitru) {
		this.khaitru = khaitru;
	}
	

	@Column(name = "Diachi", length = 300)
	public String getDiachi() {
		return this.diachi;
	}

	public void setDiachi(String diachi) {
		this.diachi = diachi;
	}

	@Column(name = "SDT", length = 15)
	public String getSdt() {
		return this.sdt;
	}

	public void setSdt(String sdt) {
		this.sdt = sdt;
	}

	@Column(name = "password", length = 150)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taikhoan")
	public Set<Doanphi> getDoanphis() {
		return this.doanphis;
	}

	public void setDoanphis(Set<Doanphi> doanphis) {
		this.doanphis = doanphis;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taikhoan")
	public Set<Diemdv> getDiemdvs() {
		return this.diemdvs;
	}

	public void setDiemdvs(Set<Diemdv> diemdvs) {
		this.diemdvs = diemdvs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taikhoan")
	public Set<Tintuc> getTintucs() {
		return this.tintucs;
	}

	public void setTintucs(Set<Tintuc> tintucs) {
		this.tintucs = tintucs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taikhoan")
	public Set<CtHoatdong> getCtHoatdongs() {
		return this.ctHoatdongs;
	}

	public void setCtHoatdongs(Set<CtHoatdong> ctHoatdongs) {
		this.ctHoatdongs = ctHoatdongs;
	}

}
