package com.QLDVSpringMVC.model;
// Generated 22-May-2021, 2:33:20 pm by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tieuchi generated by hbm2java
 */
@Entity
@Table(name = "tieuchi", catalog = "quanlydoanvien")
public class Tieuchi implements java.io.Serializable {

	private int maTc;
	private String nd;
	private Integer mucDiem;
	private Boolean trangthai;
	private Set<TieuchiDiemrenluyen> tieuchiDiemrenluyens = new HashSet<TieuchiDiemrenluyen>(0);

	public Tieuchi() {
	}

	public Tieuchi(int maTc) {
		this.maTc = maTc;
	}

	public Tieuchi(int maTc, String nd, Integer mucDiem, Boolean trangthai,
			Set<TieuchiDiemrenluyen> tieuchiDiemrenluyens) {
		this.maTc = maTc;
		this.nd = nd;
		this.mucDiem = mucDiem;
		this.trangthai = trangthai;
		this.tieuchiDiemrenluyens = tieuchiDiemrenluyens;
	}

	@Id

	@Column(name = "MaTC", unique = true, nullable = false)
	public int getMaTc() {
		return this.maTc;
	}

	public void setMaTc(int maTc) {
		this.maTc = maTc;
	}

	@Column(name = "ND", length = 250)
	public String getNd() {
		return this.nd;
	}

	public void setNd(String nd) {
		this.nd = nd;
	}

	@Column(name = "MucDiem")
	public Integer getMucDiem() {
		return this.mucDiem;
	}

	public void setMucDiem(Integer mucDiem) {
		this.mucDiem = mucDiem;
	}

	@Column(name = "Trangthai")
	public Boolean getTrangthai() {
		return this.trangthai;
	}

	public void setTrangthai(Boolean trangthai) {
		this.trangthai = trangthai;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tieuchi")
	public Set<TieuchiDiemrenluyen> getTieuchiDiemrenluyens() {
		return this.tieuchiDiemrenluyens;
	}

	public void setTieuchiDiemrenluyens(Set<TieuchiDiemrenluyen> tieuchiDiemrenluyens) {
		this.tieuchiDiemrenluyens = tieuchiDiemrenluyens;
	}

}
